name: "Image Converter"
description: "Image Converter"
version: "0.0.1"
slug: "image_converter"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: before
ports:
  9000/tcp: 9000
